// Package generation builds, stores and switches immutable configuration
// generations. A generation is a directory of complete application config
// files plus the manifest describing how it was produced.
package generation

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

// ManifestName is the file every generation carries at its root.
const ManifestName = "manifest.toml"

// Manifest records what a generation contains and where it came from, so a
// generation stays self-describing even if config.toml changes afterwards.
type Manifest struct {
	Generation  int       `toml:"generation"`
	CreatedAt   time.Time `toml:"created_at"`
	Theme       string    `toml:"theme"`
	ThemeSource string    `toml:"theme_source,omitempty"`
	RiceVersion string    `toml:"rice_version"`
	Parent      int       `toml:"parent_generation,omitempty"`
	Description string    `toml:"description,omitempty"`

	Components []string `toml:"components"`
	Files      []File   `toml:"files"`
}

// File is one generated configuration file and its content hash, which is what
// makes it possible to tell whether a generation was tampered with.
type File struct {
	Path   string `toml:"path"`
	SHA256 string `toml:"sha256"`
	Reload string `toml:"reload"`
}

// WriteManifest writes the manifest into a generation directory.
func WriteManifest(dir string, m Manifest) error {
	data, err := toml.Marshal(m)
	if err != nil {
		return fmt.Errorf("encode manifest: %w", err)
	}
	header := fmt.Sprintf("# Generated by Rice %s. Do not edit.\n\n", m.RiceVersion)
	path := filepath.Join(dir, ManifestName)
	if err := os.WriteFile(path, append([]byte(header), data...), 0o644); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}
	return nil
}

// ReadManifest loads the manifest from a generation directory.
func ReadManifest(dir string) (Manifest, error) {
	path := filepath.Join(dir, ManifestName)
	data, err := os.ReadFile(path)
	if err != nil {
		return Manifest{}, fmt.Errorf("read manifest: %w", err)
	}
	var m Manifest
	if err := toml.Unmarshal(data, &m); err != nil {
		return Manifest{}, fmt.Errorf("parse %s: %w", path, err)
	}
	return m, nil
}

// Summary is a one-line description used by `rice generation list`.
func (m Manifest) Summary() string {
	parts := []string{m.Theme}
	if m.Description != "" {
		parts = append(parts, m.Description)
	}
	return strings.Join(parts, " — ")
}
